INSERT INTO exercises (id, name, category, muscle_group, description, user_id) VALUES
    (RANDOM_UUID(), 'Bench Press', 'CHEST', 'Pectoralis Major', 'Barbell flat bench press', NULL),
    (RANDOM_UUID(), 'Incline Dumbbell Press', 'CHEST', 'Upper Chest', 'Incline DB press at 45 degrees', NULL),
    (RANDOM_UUID(), 'Cable Fly', 'CHEST', 'Pectoralis Minor', 'Cable crossover chest fly', NULL),
    (RANDOM_UUID(), 'Dips', 'CHEST', 'Lower Chest', 'Parallel bar dips for chest', NULL),
    (RANDOM_UUID(), 'Pull-Up', 'BACK', 'Latissimus Dorsi', 'Bodyweight pull-up to chin above bar', NULL),
    (RANDOM_UUID(), 'Barbell Row', 'BACK', 'Rhomboids', 'Bent-over barbell row, overhand grip', NULL),
    (RANDOM_UUID(), 'Lat Pulldown', 'BACK', 'Latissimus Dorsi', 'Cable lat pulldown to chest', NULL),
    (RANDOM_UUID(), 'Seated Cable Row', 'BACK', 'Middle Back', 'Seated cable row with close grip', NULL),
    (RANDOM_UUID(), 'Face Pull', 'BACK', 'Rear Deltoids', 'Cable face pull for rear delts and rotator cuff', NULL),
    (RANDOM_UUID(), 'Squat', 'LEGS', 'Quadriceps', 'Barbell back squat, hip-width stance', NULL),
    (RANDOM_UUID(), 'Deadlift', 'LEGS', 'Hamstrings', 'Conventional deadlift, double overhand', NULL),
    (RANDOM_UUID(), 'Leg Press', 'LEGS', 'Quadriceps', '45-degree leg press machine', NULL),
    (RANDOM_UUID(), 'Romanian Deadlift', 'LEGS', 'Hamstrings', 'Barbell RDL for hamstring stretch', NULL),
    (RANDOM_UUID(), 'Leg Curl', 'LEGS', 'Hamstrings', 'Lying or seated hamstring curl machine', NULL),
    (RANDOM_UUID(), 'Calf Raise', 'LEGS', 'Gastrocnemius', 'Standing calf raise on machine or step', NULL),
    (RANDOM_UUID(), 'Overhead Press', 'SHOULDERS', 'Anterior Deltoids', 'Standing barbell overhead press', NULL),
    (RANDOM_UUID(), 'Lateral Raise', 'SHOULDERS', 'Lateral Deltoids', 'Dumbbell lateral raise for side delts', NULL),
    (RANDOM_UUID(), 'Front Raise', 'SHOULDERS', 'Anterior Deltoids', 'Dumbbell front raise', NULL),
    (RANDOM_UUID(), 'Arnold Press', 'SHOULDERS', 'Deltoids', 'Dumbbell Arnold press with rotation', NULL),
    (RANDOM_UUID(), 'Bicep Curl', 'ARMS', 'Biceps Brachii', 'Standing dumbbell bicep curl', NULL),
    (RANDOM_UUID(), 'Hammer Curl', 'ARMS', 'Brachialis', 'Neutral-grip hammer curl', NULL),
    (RANDOM_UUID(), 'Tricep Pushdown', 'ARMS', 'Triceps Brachii', 'Cable tricep pushdown with rope', NULL),
    (RANDOM_UUID(), 'Skull Crusher', 'ARMS', 'Triceps Long Head', 'EZ-bar skull crusher lying on bench', NULL),
    (RANDOM_UUID(), 'Preacher Curl', 'ARMS', 'Biceps Short Head', 'EZ-bar preacher curl on pad', NULL),
    (RANDOM_UUID(), 'Plank', 'CORE', 'Transverse Abdominis', 'Isometric forearm plank hold', NULL),
    (RANDOM_UUID(), 'Cable Crunch', 'CORE', 'Rectus Abdominis', 'Kneeling cable crunch', NULL),
    (RANDOM_UUID(), 'Hanging Leg Raise', 'CORE', 'Hip Flexors', 'Hanging straight-leg raise from pull-up bar', NULL),
    (RANDOM_UUID(), 'Russian Twist', 'CORE', 'Obliques', 'Seated Russian twist with plate or medicine ball', NULL),
    (RANDOM_UUID(), 'Running', 'CARDIO', 'Cardiovascular', 'Treadmill or outdoor steady-state running', NULL),
    (RANDOM_UUID(), 'Cycling', 'CARDIO', 'Cardiovascular', 'Stationary bike or outdoor cycling', NULL);
